### ISSUE TITLE
Unable to use tilelink example

### ISSUE THREAD

**Issue by maarquitos14** [Microsoft/ivy#2] opened 2016-05-13 11:53 UTC
Hello,

First of all, I am unable even to execute: 
`ivy client_server.ivy`
It returns this traceback:
```
Traceback (most recent call last):
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy.py", line 107, in <module>
    ui_main_loop(ivy_init())
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy.py", line 96, in ivy_init
    source_file(fn,f)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy.py", line 64, in source_file
    ivy_load_file(f,**kwargs)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_compiler.py", line 481, in ivy_load_file
    decls = read_module(f)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_compiler.py", line 459, in read_module
    decls = parse(s,nested)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_parser.py", line 980, in parse
    res = copy.copy(parser).parse(s,lexer=copy.copy(lexer))
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_parser.py", line 890, in p_expr_tilda_atom
    p[0] = NamedSpace(~p[2].lit)
AttributeError: 'ProductSpace' object has no attribute 'lit'
```

Also, concerning the tilelink example, the README inside ivy/examples/tilelink/unit_test says doing `make` should create two binaries, however, file tilelink_two_port_tester.ivy is not in the directory. I tried copying it from ivy/examples/tilelink/unit_test/single_client as well as doing `make` inside the directory where the file actually exists. The result of the `make` in both cases is the following:
```
ivy_to_cpp isolate=iso_b tilelink_two_port_tester.ivy
error: wrong number of arguments to module tl_interface
Traceback (most recent call last):
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_to_cpp.py", line 1256, in <module>
    ivy.ivy_init()
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy.py", line 96, in ivy_init
    source_file(fn,f)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy.py", line 64, in source_file
    ivy_load_file(f,**kwargs)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_compiler.py", line 481, in ivy_load_file
    decls = read_module(f)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_compiler.py", line 459, in read_module
    decls = parse(s,nested)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_parser.py", line 980, in parse
    res = copy.copy(parser).parse(s,lexer=copy.copy(lexer))
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/local/lib/python2.7/dist-packages/ply/yacc.py", line 1106, in parseopt_notrack
    p.callable(pslice)
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_parser.py", line 185, in p_top_instantiate_insts
    do_insts(p[0],p[3])
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_parser.py", line 76, in do_insts
    raise iu.IvyError(instantiation,"wrong number of arguments to module {}".format(inst.relname))
  File "/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/src/ivy/ivy_utils.py", line 197, in __init__
    assert False
AssertionError
Makefile:9: recipe for target 'tilelink_two_port_tester.h' failed
make: *** [tilelink_two_port_tester.h] Error 1

```

Can you help me to generate the binaries? 

Thank you in advance.

**Comment by kenmcmil** [comment] 2016-05-13 16:08
I probably need to make a stable branch. Hopefully today...

**Comment by kenmcmil** [comment] 2016-05-13 18:26
I checked in a fix for these problems on master. The Makefile for the unit tester contained an old target. The targets you actually want are test_L2HellaCacheBank and test_L2BroadcastHub. I think, though, that you may need you use my fork of uncore to get the necessary configurations for the unit tester, since the unit-test branch is out-of-date. I will look into this and try to put together some instructions.

**Comment by kenmcmil** [comment] 2016-05-13 18:43
I added some instructions to examples/tilelink/unit_test/README. Let me know if they work, since I can't test them now.

**Comment by maarquitos14** [comment] 2016-05-13 20:09
I have been able to advance much more now. At least, I don't get python errors. I have successfully executed `ivy client_server.ivy`.

With respecto to the tilelink, I have followed your new instructions, including changing the remote url to your fork. It did not work for me, I got the following output:
```
marcos@marcos-Latitude-E7440:~/FIB/MIRI/QP_15-16/MA/riscv/ivy/examples/tilelink/unit_test$ make test_L2HellaCacheBank 
install -d L2HellaCacheBank
export CXX='g++ -g' && cd /media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/rocket-chip-master/rocket-chip/ && sbt "project uncore" "run L2HellaCacheBank DefaultL2Config --backend c --genHarness --compile --debug --vcd --ioDebug --targetDir /media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/examples/tilelink/unit_test/L2HellaCacheBank"
[info] Loading project definition from /media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/rocket-chip-master/rocket-chip/project
Using addons: 
[info] Set current project to rocketchip (in build file:/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/rocket-chip-master/rocket-chip/)
[info] Set current project to uncore (in build file:/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/rocket-chip-master/rocket-chip/)
[info] Compiling 20 Scala sources to /media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/rocket-chip-master/rocket-chip/uncore/target/scala-2.11/classes...
[error] /media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/rocket-chip-master/rocket-chip/uncore/src/main/scala/converters.scala:462: overloaded method value apply with alternatives:
[error]   (data: Chisel.UInt,strb: Chisel.UInt,last: Chisel.Bool,id: Chisel.UInt)(implicit p: cde.Parameters)junctions.NastiWriteDataChannel <and>
[error]   (data: Chisel.UInt,last: Chisel.Bool,id: Chisel.UInt)(implicit p: cde.Parameters)junctions.NastiWriteDataChannel
[error]  cannot be applied to (data: Chisel.UInt, strb: Chisel.UInt, last: Chisel.Bool)
[error]   io.nasti.w.bits := NastiWriteDataChannel(
[error]                      ^
[error] /media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/rocket-chip-master/rocket-chip/uncore/src/main/scala/scr.scala:4: object MMIOBase is not a member of package junctions
[error] import junctions.{SmiIO, MMIOBase}
[error]        ^
[error] two errors found
[error] (uncore/compile:compileIncremental) Compilation failed
[error] Total time: 13 s, completed May 13, 2016 10:01:39 PM
Makefile:46: recipe for target 'L2HellaCacheBank/L2HellaCacheBank.o' failed
make: *** [L2HellaCacheBank/L2HellaCacheBank.o] Error 1
```

Thank you for your time and fast answer.

**Comment by kenmcmil** [comment] 2016-05-13 21:11
Probably my fork needs updating w.r.t. rocketchip master. Let me know what commit of rocketchip you're using. I can probably look at this on Tuesday. Meanwhile you might try merging changes from uncore into my branch.

**Comment by maarquitos14** [comment] 2016-05-17 07:08
I am in this commit right now: `cf26267f0ada1ce5957b9815d25a48e2c44c5af2`.

I have been trying to do the merge by myself but after solving conflicts I get another errors when performing `make test_L2HellaCacheBank` like those listed following:

```
marcos@marcos-Latitude-E7440:/media/marcos/6f3d3766-82c3-49e1-8e67-22d2e9d02b22/FIB/MIRI/QP_15-16/MA/riscv/ivy/examples/tilelink/unit_test$ make test_L2HellaCacheBank
sed -e 's/managerEndpoint_//g' -e 's/L2Unit_/L2HellaCacheBank_/g' tilelink_coherence_manager.cpp > tilelink_coherence_manager_hella.cpp
g++ -g -I /include -I L2HellaCacheBank -L /lib -o test_L2HellaCacheBank main.cpp tilelink_coherence_manager_tester.cpp hash.cpp tilelink_hella_cache.cpp L2HellaCacheBank/L2HellaCacheBank.o -lz3
main.cpp: In function ‘int main(int, const char**)’:
main.cpp:371:20: error: ‘class tilelink_coherence_manager_tester’ has no member named ‘ref__perform’
                 tb.ref__perform(acq_c.ltime_,tb.buf_id);
                    ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__b__tl_Finish(int)’:
tilelink_coherence_manager_tester.cpp:31:26: error: ‘fnss__cid’ was not declared in this scope
                 loc__c = fnss__cid[msg];
                          ^
tilelink_coherence_manager_tester.cpp:32:29: error: ‘fnss__id_’ was not declared in this scope
                 loc__txid = fnss__id_[msg];
                             ^
tilelink_coherence_manager_tester.cpp:33:27: error: ‘fnss__addr_hi’ was not declared in this scope
                 loc__hi = fnss__addr_hi[msg];
                           ^
tilelink_coherence_manager_tester.cpp:34:27: error: ‘fnss__word’ was not declared in this scope
                 loc__lo = fnss__word[msg];
                           ^
tilelink_coherence_manager_tester.cpp:35:27: error: ‘fnss__own’ was not declared in this scope
                 loc__ow = fnss__own[msg];
                           ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__b__tl_Acquire(int)’:
tilelink_coherence_manager_tester.cpp:77:26: error: ‘acqs__cid’ was not declared in this scope
                 loc__c = acqs__cid[msg];
                          ^
tilelink_coherence_manager_tester.cpp:78:27: error: ‘acqs__own’ was not declared in this scope
                 loc__ow = acqs__own[msg];
                           ^
tilelink_coherence_manager_tester.cpp:79:27: error: ‘acqs__addr_hi’ was not declared in this scope
                 loc__hi = acqs__addr_hi[msg];
                           ^
tilelink_coherence_manager_tester.cpp:80:27: error: ‘acqs__word’ was not declared in this scope
                 loc__lo = acqs__word[msg];
                           ^
tilelink_coherence_manager_tester.cpp:81:29: error: ‘acqs__id_’ was not declared in this scope
                 loc__txid = acqs__id_[msg];
                             ^
tilelink_coherence_manager_tester.cpp:82:27: error: ‘acqs__ltime_’ was not declared in this scope
                 loc__lt = acqs__ltime_[msg];
                           ^
tilelink_coherence_manager_tester.cpp:84:26: error: ‘acqs__data_’ was not declared in this scope
                 loc__d = acqs__data_[msg];
                          ^
tilelink_coherence_manager_tester.cpp:85:26: error: ‘acqs__op’ was not declared in this scope
                 loc__o = acqs__op[msg];
                          ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__m__probe(int, int, int)’:
tilelink_coherence_manager_tester.cpp:195:13: error: ‘prbs__cid’ was not declared in this scope
             prbs__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:196:13: error: ‘prbs__id_’ was not declared in this scope
             prbs__id_[loc__a] = id_;
             ^
tilelink_coherence_manager_tester.cpp:197:13: error: ‘prbs__addr_hi’ was not declared in this scope
             prbs__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__c__acquire(int, int, int, int, int, int, int, int, int)’:
tilelink_coherence_manager_tester.cpp:209:13: error: ‘acqs__cid’ was not declared in this scope
             acqs__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:210:13: error: ‘acqs__id_’ was not declared in this scope
             acqs__id_[loc__a] = id_;
             ^
tilelink_coherence_manager_tester.cpp:211:13: error: ‘acqs__addr_hi’ was not declared in this scope
             acqs__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp:212:13: error: ‘acqs__word’ was not declared in this scope
             acqs__word[loc__a] = word;
             ^
tilelink_coherence_manager_tester.cpp:213:13: error: ‘acqs__own’ was not declared in this scope
             acqs__own[loc__a] = own;
             ^
tilelink_coherence_manager_tester.cpp:214:13: error: ‘acqs__op’ was not declared in this scope
             acqs__op[loc__a] = op;
             ^
tilelink_coherence_manager_tester.cpp:215:13: error: ‘acqs__data_’ was not declared in this scope
             acqs__data_[loc__a] = data_;
             ^
tilelink_coherence_manager_tester.cpp:216:13: error: ‘acqs__block’ was not declared in this scope
             acqs__block[loc__a] = block;
             ^
tilelink_coherence_manager_tester.cpp:217:13: error: ‘acqs__ltime_’ was not declared in this scope
             acqs__ltime_[loc__a] = ltime_;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::c__tl_Probe(int)’:
tilelink_coherence_manager_tester.cpp:232:26: error: ‘prbs__cid’ was not declared in this scope
                 loc__c = prbs__cid[msg];
                          ^
tilelink_coherence_manager_tester.cpp:233:27: error: ‘prbs__addr_hi’ was not declared in this scope
                 loc__hi = prbs__addr_hi[msg];
                           ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__b__acquire(int, int, int, int, int, int, int, int, int)’:
tilelink_coherence_manager_tester.cpp:267:13: error: ‘acqs__cid’ was not declared in this scope
             acqs__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:268:13: error: ‘acqs__id_’ was not declared in this scope
             acqs__id_[loc__a] = id_;
             ^
tilelink_coherence_manager_tester.cpp:269:13: error: ‘acqs__addr_hi’ was not declared in this scope
             acqs__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp:270:13: error: ‘acqs__word’ was not declared in this scope
             acqs__word[loc__a] = word;
             ^
tilelink_coherence_manager_tester.cpp:271:13: error: ‘acqs__own’ was not declared in this scope
             acqs__own[loc__a] = own;
             ^
tilelink_coherence_manager_tester.cpp:272:13: error: ‘acqs__op’ was not declared in this scope
             acqs__op[loc__a] = op;
             ^
tilelink_coherence_manager_tester.cpp:273:13: error: ‘acqs__data_’ was not declared in this scope
             acqs__data_[loc__a] = data_;
             ^
tilelink_coherence_manager_tester.cpp:274:13: error: ‘acqs__block’ was not declared in this scope
             acqs__block[loc__a] = block;
             ^
tilelink_coherence_manager_tester.cpp:275:13: error: ‘acqs__ltime_’ was not declared in this scope
             acqs__ltime_[loc__a] = ltime_;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__b__probe(int, int, int)’:
tilelink_coherence_manager_tester.cpp:669:13: error: ‘prbs__cid’ was not declared in this scope
             prbs__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:670:13: error: ‘prbs__id_’ was not declared in this scope
             prbs__id_[loc__a] = id_;
             ^
tilelink_coherence_manager_tester.cpp:671:13: error: ‘prbs__addr_hi’ was not declared in this scope
             prbs__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::c__tl_Grant(int)’:
tilelink_coherence_manager_tester.cpp:727:26: error: ‘gnts__cid’ was not declared in this scope
                 loc__c = gnts__cid[msg];
                          ^
tilelink_coherence_manager_tester.cpp:728:27: error: ‘gnts__addr_hi’ was not declared in this scope
                 loc__hi = gnts__addr_hi[msg];
                           ^
tilelink_coherence_manager_tester.cpp:729:27: error: ‘gnts__word’ was not declared in this scope
                 loc__lo = gnts__word[msg];
                           ^
tilelink_coherence_manager_tester.cpp:730:31: error: ‘gnts__clnt_txid’ was not declared in this scope
                 loc__c_txid = gnts__clnt_txid[msg];
                               ^
tilelink_coherence_manager_tester.cpp:731:31: error: ‘gnts__mngr_txid’ was not declared in this scope
                 loc__m_txid = gnts__mngr_txid[msg];
                               ^
tilelink_coherence_manager_tester.cpp:732:27: error: ‘gnts__own’ was not declared in this scope
                 loc__ow = gnts__own[msg];
                           ^
tilelink_coherence_manager_tester.cpp:733:27: error: ‘gnts__ltime_’ was not declared in this scope
                 loc__lt = gnts__ltime_[msg];
                           ^
tilelink_coherence_manager_tester.cpp:735:20: error: ‘gnts__relack’ was not declared in this scope
                 if(gnts__relack[msg]){
                    ^
tilelink_coherence_manager_tester.cpp:890:71: error: ‘gnts__data_’ was not declared in this scope
                                 front__abs__grant(loc__c, loc__maddr, gnts__data_[msg], loc__ow);
                                                                       ^
tilelink_coherence_manager_tester.cpp:920:74: error: ‘gnts__data_’ was not declared in this scope
                                 front__abs__response(loc__c, loc__maddr, gnts__data_[msg], ref__evs__type_[loc__lt], loc__lt);
                                                                          ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__b__release(int, int, int, int, int, int, int)’:
tilelink_coherence_manager_tester.cpp:938:13: error: ‘rlss__cid’ was not declared in this scope
             rlss__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:939:13: error: ‘rlss__id_’ was not declared in this scope
             rlss__id_[loc__a] = id_;
             ^
tilelink_coherence_manager_tester.cpp:940:13: error: ‘rlss__voluntary’ was not declared in this scope
             rlss__voluntary[loc__a] = voluntary;
             ^
tilelink_coherence_manager_tester.cpp:941:13: error: ‘rlss__addr_hi’ was not declared in this scope
             rlss__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp:942:13: error: ‘rlss__word’ was not declared in this scope
             rlss__word[loc__a] = word;
             ^
tilelink_coherence_manager_tester.cpp:943:13: error: ‘rlss__dirty’ was not declared in this scope
             rlss__dirty[loc__a] = dirty;
             ^
tilelink_coherence_manager_tester.cpp:944:13: error: ‘rlss__data_’ was not declared in this scope
             rlss__data_[loc__a] = data_;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__c__release(int, int, int, int, int, int, int)’:
tilelink_coherence_manager_tester.cpp:963:13: error: ‘rlss__cid’ was not declared in this scope
             rlss__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:964:13: error: ‘rlss__id_’ was not declared in this scope
             rlss__id_[loc__a] = id_;
             ^
tilelink_coherence_manager_tester.cpp:965:13: error: ‘rlss__voluntary’ was not declared in this scope
             rlss__voluntary[loc__a] = voluntary;
             ^
tilelink_coherence_manager_tester.cpp:966:13: error: ‘rlss__addr_hi’ was not declared in this scope
             rlss__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp:967:13: error: ‘rlss__word’ was not declared in this scope
             rlss__word[loc__a] = word;
             ^
tilelink_coherence_manager_tester.cpp:968:13: error: ‘rlss__dirty’ was not declared in this scope
             rlss__dirty[loc__a] = dirty;
             ^
tilelink_coherence_manager_tester.cpp:969:13: error: ‘rlss__data_’ was not declared in this scope
             rlss__data_[loc__a] = data_;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__m__grant(int, int, int, int, int, int, int, int, int)’:
tilelink_coherence_manager_tester.cpp:981:13: error: ‘gnts__cid’ was not declared in this scope
             gnts__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:982:13: error: ‘gnts__clnt_txid’ was not declared in this scope
             gnts__clnt_txid[loc__a] = clnt_txid;
             ^
tilelink_coherence_manager_tester.cpp:983:13: error: ‘gnts__mngr_txid’ was not declared in this scope
             gnts__mngr_txid[loc__a] = mngr_txid;
             ^
tilelink_coherence_manager_tester.cpp:984:13: error: ‘gnts__word’ was not declared in this scope
             gnts__word[loc__a] = word;
             ^
tilelink_coherence_manager_tester.cpp:985:13: error: ‘gnts__own’ was not declared in this scope
             gnts__own[loc__a] = own;
             ^
tilelink_coherence_manager_tester.cpp:986:13: error: ‘gnts__relack’ was not declared in this scope
             gnts__relack[loc__a] = relack;
             ^
tilelink_coherence_manager_tester.cpp:987:13: error: ‘gnts__data_’ was not declared in this scope
             gnts__data_[loc__a] = data_;
             ^
tilelink_coherence_manager_tester.cpp:988:13: error: ‘gnts__addr_hi’ was not declared in this scope
             gnts__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp:989:13: error: ‘gnts__ltime_’ was not declared in this scope
             gnts__ltime_[loc__a] = ltime_;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__c__finish(int, int, int, int, int)’:
tilelink_coherence_manager_tester.cpp:1046:13: error: ‘fnss__cid’ was not declared in this scope
             fnss__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:1047:13: error: ‘fnss__id_’ was not declared in this scope
             fnss__id_[loc__a] = id_;
             ^
tilelink_coherence_manager_tester.cpp:1048:13: error: ‘fnss__addr_hi’ was not declared in this scope
             fnss__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp:1049:13: error: ‘fnss__word’ was not declared in this scope
             fnss__word[loc__a] = word;
             ^
tilelink_coherence_manager_tester.cpp:1050:13: error: ‘fnss__own’ was not declared in this scope
             fnss__own[loc__a] = own;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__b__tl_Release(int)’:
tilelink_coherence_manager_tester.cpp:1073:26: error: ‘rlss__cid’ was not declared in this scope
                 loc__c = rlss__cid[msg];
                          ^
tilelink_coherence_manager_tester.cpp:1074:29: error: ‘rlss__id_’ was not declared in this scope
                 loc__txid = rlss__id_[msg];
                             ^
tilelink_coherence_manager_tester.cpp:1075:26: error: ‘rlss__data_’ was not declared in this scope
                 loc__d = rlss__data_[msg];
                          ^
tilelink_coherence_manager_tester.cpp:1076:27: error: ‘rlss__addr_hi’ was not declared in this scope
                 loc__hi = rlss__addr_hi[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1077:27: error: ‘rlss__word’ was not declared in this scope
                 loc__lo = rlss__word[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1081:63: error: ‘rlss__dirty’ was not declared in this scope
                 ivy_assume((!front__dirt_p[loc__c][loc__a] || rlss__dirty[msg]));
                                                               ^
tilelink_coherence_manager_tester.cpp:1103:20: error: ‘rlss__voluntary’ was not declared in this scope
                 if(rlss__voluntary[msg]){
                    ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__b__tl_Grant(int)’:
tilelink_coherence_manager_tester.cpp:1251:27: error: ‘gnts__addr_hi’ was not declared in this scope
                 loc__hi = gnts__addr_hi[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1252:27: error: ‘gnts__word’ was not declared in this scope
                 loc__lo = gnts__word[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1253:31: error: ‘gnts__clnt_txid’ was not declared in this scope
                 loc__c_txid = gnts__clnt_txid[msg];
                               ^
tilelink_coherence_manager_tester.cpp:1254:31: error: ‘gnts__mngr_txid’ was not declared in this scope
                 loc__m_txid = gnts__mngr_txid[msg];
                               ^
tilelink_coherence_manager_tester.cpp:1255:27: error: ‘gnts__own’ was not declared in this scope
                 loc__ow = gnts__own[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1256:27: error: ‘gnts__ltime_’ was not declared in this scope
                 loc__lt = gnts__ltime_[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1258:51: error: ‘gnts__relack’ was not declared in this scope
                 ivy_assume(((loc__ow == none) && !gnts__relack[msg]));
                                                   ^
tilelink_coherence_manager_tester.cpp:1299:59: error: ‘gnts__data_’ was not declared in this scope
                 ivy_assume((!!back__dirty[loc__maddr] || (gnts__data_[msg] == ref__mem[loc__maddr])));
                                                           ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__b__grant(int, int, int, int, int, int, int, int, int)’:
tilelink_coherence_manager_tester.cpp:1328:13: error: ‘gnts__cid’ was not declared in this scope
             gnts__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:1329:13: error: ‘gnts__clnt_txid’ was not declared in this scope
             gnts__clnt_txid[loc__a] = clnt_txid;
             ^
tilelink_coherence_manager_tester.cpp:1330:13: error: ‘gnts__mngr_txid’ was not declared in this scope
             gnts__mngr_txid[loc__a] = mngr_txid;
             ^
tilelink_coherence_manager_tester.cpp:1331:13: error: ‘gnts__word’ was not declared in this scope
             gnts__word[loc__a] = word;
             ^
tilelink_coherence_manager_tester.cpp:1332:13: error: ‘gnts__own’ was not declared in this scope
             gnts__own[loc__a] = own;
             ^
tilelink_coherence_manager_tester.cpp:1333:13: error: ‘gnts__relack’ was not declared in this scope
             gnts__relack[loc__a] = relack;
             ^
tilelink_coherence_manager_tester.cpp:1334:13: error: ‘gnts__data_’ was not declared in this scope
             gnts__data_[loc__a] = data_;
             ^
tilelink_coherence_manager_tester.cpp:1335:13: error: ‘gnts__addr_hi’ was not declared in this scope
             gnts__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp:1336:13: error: ‘gnts__ltime_’ was not declared in this scope
             gnts__ltime_[loc__a] = ltime_;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::ext__b__finish(int, int, int, int, int)’:
tilelink_coherence_manager_tester.cpp:1460:13: error: ‘fnss__cid’ was not declared in this scope
             fnss__cid[loc__a] = cid;
             ^
tilelink_coherence_manager_tester.cpp:1461:13: error: ‘fnss__id_’ was not declared in this scope
             fnss__id_[loc__a] = id_;
             ^
tilelink_coherence_manager_tester.cpp:1462:13: error: ‘fnss__addr_hi’ was not declared in this scope
             fnss__addr_hi[loc__a] = addr_hi;
             ^
tilelink_coherence_manager_tester.cpp:1463:13: error: ‘fnss__word’ was not declared in this scope
             fnss__word[loc__a] = word;
             ^
tilelink_coherence_manager_tester.cpp:1464:13: error: ‘fnss__own’ was not declared in this scope
             fnss__own[loc__a] = own;
             ^
tilelink_coherence_manager_tester.cpp: In member function ‘void tilelink_coherence_manager_tester::m__tl_Acquire(int)’:
tilelink_coherence_manager_tester.cpp:1493:27: error: ‘acqs__own’ was not declared in this scope
                 loc__ow = acqs__own[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1494:27: error: ‘acqs__addr_hi’ was not declared in this scope
                 loc__hi = acqs__addr_hi[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1495:27: error: ‘acqs__word’ was not declared in this scope
                 loc__lo = acqs__word[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1496:29: error: ‘acqs__id_’ was not declared in this scope
                 loc__txid = acqs__id_[msg];
                             ^
tilelink_coherence_manager_tester.cpp:1497:27: error: ‘acqs__ltime_’ was not declared in this scope
                 loc__lt = acqs__ltime_[msg];
                           ^
tilelink_coherence_manager_tester.cpp:1499:26: error: ‘acqs__data_’ was not declared in this scope
                 loc__d = acqs__data_[msg];
                          ^
tilelink_coherence_manager_tester.cpp:1500:26: error: ‘acqs__op’ was not declared in this scope
                 loc__o = acqs__op[msg];
                          ^
tilelink_coherence_manager_tester.cpp:1501:27: error: ‘acqs__block’ was not declared in this scope
                 loc__bl = acqs__block[msg];
                           ^
Makefile:56: recipe for target 'test_L2HellaCacheBank' failed
make: *** [test_L2HellaCacheBank] Error 1
```

Thank you.

**Comment by kenmcmil** [comment] 2016-05-17 18:40
OK, I've fixed a few regressions in Ivy. Pull the latest from master (commit cba39d3). I tested this with the master branch of fork kenmcmil/uncore and it at least compiles and runs (I don't know if it's giving correct answers). It should probably also work with the other branches mentioned in the README. 

By the way, the only difference between my fork of uncore and the upstream is the file src/main/scala/builder.scala, which contains the necessary configs (courtesy of Henry).

Let me know if you can get the tester to build and run.

**Comment by kenmcmil** [comment] 2016-05-18 00:31
I've done some cleanup and improved the instructions in the README a bit. Things seem to be working, so I am closing this issue. Please re-open is you still have problems.

**Closed by kenmcmil** 2016-05-18 00:31 UTC

**Comment by maarquitos14** [comment] 2016-05-18 07:29
Finally I have been able to get the binaries. However, I get an `assert failed` when I run `./test_L2HellaCacheBank`. 

By the way, I would like to know if there is any possibility of changing the protocol to be verified and how, if there is any.

**Comment by kenmcmil** [comment] 2016-05-18 16:57
Yes, I get an assert failed as well for seed 1 at clock 42. That's normal, however. It means there was some protocol violation. Have a look at the README for some information on how to debug this.

The protocol is described in file tilelink_concrete_spec.ivy. You can change it, but you need to understand the ivy language and we don't have documentation on the language yet.
